---
- name: Create Route on OCP
  hosts: localhost
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.kubernetes

  tasks:
    - name: SBBeer
      k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            labels:
              app: sb-beer
            name: sb-beer
            namespace: pipelines-ws-tekton
          spec:
            port:
              targetPort: 8080-tcp
            to:
              kind: Service
              name: sb-beer
              weight: 100
        validate_certs: false
